### ISSUE TITLE
GetFEN() and restore from FEN does not include the move histories...

### ISSUE THREAD

**Issue by nvrnight** [ProgramFOX/Chess.NET#16]
Whenever I display the game board I highlight the previous move on the board. After de-serialization it's not populating the Moves property so I'm not able to tell what the last move was.

**Comment by ProgramFOX** [comment]
Ah yes, of course... I totally forgot about the Moves property in our previous conversation. FEN doesn't contain any moves by design.

Here's my plan: a `GetSerializableObject()` method on ChessGame that returns an object with the FEN, the move list, and the three other properties that aren't in the FEN. Then a way to go back to a ChessGame from that object. I won't be able to implement that before next week though, so if you'd want to work on it already, go ahead; if not, I'll do it next week.

**Comment by nvrnight** [comment]
What if we add the missing properties to GameCreationData and make that serializable? To make it serializable we would have to add parameterless constructors to each Piece and Position and remove the protected set from its public properties, but I'd think that would be a small price to pay to re-use the existing constructor around game creation and keeping backwards compatibility.

We could then create a new function GetGameCreationData if it doesn't already exist and spit out everything needed to re-create the existing game in its current state.

**Comment by ProgramFOX** [comment]
Yes, you're right, that works too.

**Comment by nvrnight** [comment]
Alright, I'll get started on it sometime tonight probably.
